// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  HealthHealthData,
  HealthHealthResponses,
  PresignCreatePresignUrlData,
  PresignCreatePresignUrlResponses,
  QuestionCountData,
  QuestionCountResponses,
  QuestionDeleteData,
  QuestionDeleteResponses,
  QuestionGetData,
  QuestionGetResponses,
  QuestionGetSchemaData,
  QuestionGetSchemaResponses,
  QuestionReadData,
  QuestionReadResponses,
  QuestionReadWithSortingData,
  QuestionReadWithSortingResponses,
  QuestionUpsertData,
  QuestionUpsertResponses,
  SessionCountData,
  SessionCountResponses,
  SessionDeleteData,
  SessionDeleteResponses,
  SessionGetData,
  SessionGetResponses,
  SessionGetSchemaData,
  SessionGetSchemaResponses,
  SessionReadData,
  SessionReadResponses,
  SessionReadWithSortingData,
  SessionReadWithSortingResponses,
  SessionUpsertData,
  SessionUpsertResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class SessionController {
  public static sessionRead<ThrowOnError extends boolean = false>(
    options?: Options<SessionReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SessionReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions", ...options });
  }

  public static sessionUpsert<ThrowOnError extends boolean = false>(
    options: Options<SessionUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      SessionUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/sessions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static sessionDelete<ThrowOnError extends boolean = false>(
    options: Options<SessionDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      SessionDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}", ...options });
  }

  public static sessionGet<ThrowOnError extends boolean = false>(
    options: Options<SessionGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SessionGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}", ...options });
  }

  public static sessionReadWithSorting<ThrowOnError extends boolean = false>(
    options: Options<SessionReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SessionReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/sorted", ...options });
  }

  public static sessionGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<SessionGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SessionGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/schema", ...options });
  }

  public static sessionCount<ThrowOnError extends boolean = false>(
    options?: Options<SessionCountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SessionCountResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/count", ...options });
  }
}

export class QuestionController {
  public static questionRead<ThrowOnError extends boolean = false>(
    options?: Options<QuestionReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions", ...options });
  }

  public static questionUpsert<ThrowOnError extends boolean = false>(
    options: Options<QuestionUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      QuestionUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/questions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static questionDelete<ThrowOnError extends boolean = false>(
    options: Options<QuestionDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      QuestionDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/{id}", ...options });
  }

  public static questionGet<ThrowOnError extends boolean = false>(
    options: Options<QuestionGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      QuestionGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/{id}", ...options });
  }

  public static questionReadWithSorting<ThrowOnError extends boolean = false>(
    options: Options<QuestionReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      QuestionReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/sorted", ...options });
  }

  public static questionGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<QuestionGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/schema", ...options });
  }

  public static questionCount<ThrowOnError extends boolean = false>(
    options?: Options<QuestionCountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionCountResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/count", ...options });
  }
}

export class PresignController {
  public static presignCreatePresignUrl<ThrowOnError extends boolean = false>(
    options: Options<PresignCreatePresignUrlData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PresignCreatePresignUrlResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/presign",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class HealthController {
  public static healthHealth<ThrowOnError extends boolean = false>(
    options?: Options<HealthHealthData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      HealthHealthResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/health",
      ...options,
    });
  }
}
