// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AvailableEventsData,
  AvailableEventsResponses,
  CountData,
  CountResponses,
  DebugData,
  DebugResponses,
  DeleteData,
  DeleteResponses,
  GetData,
  GetResponses,
  GetSchemaData,
  GetSchemaResponses,
  HealthHealthData,
  HealthHealthResponses,
  PresignCreatePresignUrlData,
  PresignCreatePresignUrlResponses,
  QuestionCountData,
  QuestionCountResponses,
  QuestionDeleteData,
  QuestionDeleteResponses,
  QuestionGetData,
  QuestionGetResponses,
  QuestionGetSchemaData,
  QuestionGetSchemaResponses,
  QuestionReadData,
  QuestionReadResponses,
  QuestionReadWithSortingData,
  QuestionReadWithSortingResponses,
  QuestionUpsertData,
  QuestionUpsertResponses,
  ReadData,
  ReadResponses,
  ReadWithSortingData,
  ReadWithSortingResponses,
  SessionstateGetStateData,
  SessionstateGetStateResponses,
  SessionstateUpsertStateData,
  SessionstateUpsertStateResponses,
  SolutionCountData,
  SolutionCountResponses,
  SolutionDeleteData,
  SolutionDeleteResponses,
  SolutionGetByQuestionIdData,
  SolutionGetByQuestionIdResponses,
  SolutionGetData,
  SolutionGetResponses,
  SolutionGetSchemaData,
  SolutionGetSchemaResponses,
  SolutionReadData,
  SolutionReadResponses,
  SolutionReadWithSortingData,
  SolutionReadWithSortingResponses,
  SolutionUpsertData,
  SolutionUpsertResponses,
  TransitionData,
  TransitionResponses,
  TutorCountData,
  TutorCountResponses,
  TutorDeleteData,
  TutorDeleteResponses,
  TutorGetActiveTutorsData,
  TutorGetActiveTutorsResponses,
  TutorGetData,
  TutorGetResponses,
  TutorGetSchemaData,
  TutorGetSchemaResponses,
  TutorReadData,
  TutorReadResponses,
  TutorReadWithSortingData,
  TutorReadWithSortingResponses,
  TutorUpsertData,
  TutorUpsertResponses,
  UpsertData,
  UpsertResponses,
  UserDeleteData,
  UserDeleteResponses,
  UserGetByEmailData,
  UserGetByEmailResponses,
  UserGetByProviderIdData,
  UserGetByProviderIdResponses,
  UserGetData,
  UserGetResponses,
  UserGetSchemaData,
  UserGetSchemaResponses,
  UserSyncUserData,
  UserSyncUserResponses,
  UserUpsertData,
  UserUpsertResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class SessionStateController {
  public static sessionstateGetState<ThrowOnError extends boolean = false>(
    options: Options<SessionstateGetStateData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SessionstateGetStateResponses,
      unknown,
      ThrowOnError
    >({ url: "/session-states", ...options });
  }

  public static sessionstateUpsertState<ThrowOnError extends boolean = false>(
    options: Options<SessionstateUpsertStateData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      SessionstateUpsertStateResponses,
      unknown,
      ThrowOnError
    >({
      url: "/session-states",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class TutorController {
  public static tutorRead<ThrowOnError extends boolean = false>(
    options?: Options<TutorReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TutorReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors", ...options });
  }

  public static tutorUpsert<ThrowOnError extends boolean = false>(
    options: Options<TutorUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      TutorUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/tutors",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static tutorDelete<ThrowOnError extends boolean = false>(
    options: Options<TutorDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      TutorDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/{id}", ...options });
  }

  public static tutorGet<ThrowOnError extends boolean = false>(
    options: Options<TutorGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      TutorGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/{id}", ...options });
  }

  public static tutorReadWithSorting<ThrowOnError extends boolean = false>(
    options: Options<TutorReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      TutorReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/sorted", ...options });
  }

  public static tutorGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<TutorGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TutorGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/schema", ...options });
  }

  public static tutorCount<ThrowOnError extends boolean = false>(
    options?: Options<TutorCountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TutorCountResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/count", ...options });
  }

  public static tutorGetActiveTutors<ThrowOnError extends boolean = false>(
    options?: Options<TutorGetActiveTutorsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TutorGetActiveTutorsResponses,
      unknown,
      ThrowOnError
    >({ url: "/tutors/active", ...options });
  }
}

export class SolutionController {
  public static solutionRead<ThrowOnError extends boolean = false>(
    options?: Options<SolutionReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SolutionReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions", ...options });
  }

  public static solutionUpsert<ThrowOnError extends boolean = false>(
    options: Options<SolutionUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      SolutionUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/solutions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static solutionDelete<ThrowOnError extends boolean = false>(
    options: Options<SolutionDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      SolutionDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/{id}", ...options });
  }

  public static solutionGet<ThrowOnError extends boolean = false>(
    options: Options<SolutionGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SolutionGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/{id}", ...options });
  }

  public static solutionReadWithSorting<ThrowOnError extends boolean = false>(
    options: Options<SolutionReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SolutionReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/sorted", ...options });
  }

  public static solutionGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<SolutionGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SolutionGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/schema", ...options });
  }

  public static solutionGetByQuestionId<ThrowOnError extends boolean = false>(
    options: Options<SolutionGetByQuestionIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      SolutionGetByQuestionIdResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/question/{questionId}", ...options });
  }

  public static solutionCount<ThrowOnError extends boolean = false>(
    options?: Options<SolutionCountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      SolutionCountResponses,
      unknown,
      ThrowOnError
    >({ url: "/solutions/count", ...options });
  }
}

export class SessionController {
  public static read<ThrowOnError extends boolean = false>(
    options?: Options<ReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions", ...options });
  }

  public static upsert<ThrowOnError extends boolean = false>(
    options: Options<UpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/sessions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static transition<ThrowOnError extends boolean = false>(
    options: Options<TransitionData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      TransitionResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}/transition", ...options });
  }

  public static delete<ThrowOnError extends boolean = false>(
    options: Options<DeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}", ...options });
  }

  public static get<ThrowOnError extends boolean = false>(
    options: Options<GetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetResponses, unknown, ThrowOnError>({
      url: "/sessions/{id}",
      ...options,
    });
  }

  public static debug<ThrowOnError extends boolean = false>(
    options: Options<DebugData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      DebugResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}/debug", ...options });
  }

  public static availableEvents<ThrowOnError extends boolean = false>(
    options: Options<AvailableEventsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      AvailableEventsResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/{id}/available-events", ...options });
  }

  public static readWithSorting<ThrowOnError extends boolean = false>(
    options: Options<ReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/sorted", ...options });
  }

  public static getSchema<ThrowOnError extends boolean = false>(
    options?: Options<GetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/schema", ...options });
  }

  public static count<ThrowOnError extends boolean = false>(
    options?: Options<CountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      CountResponses,
      unknown,
      ThrowOnError
    >({ url: "/sessions/count", ...options });
  }
}

export class QuestionController {
  public static questionRead<ThrowOnError extends boolean = false>(
    options?: Options<QuestionReadData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionReadResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions", ...options });
  }

  public static questionUpsert<ThrowOnError extends boolean = false>(
    options: Options<QuestionUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      QuestionUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/questions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static questionDelete<ThrowOnError extends boolean = false>(
    options: Options<QuestionDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      QuestionDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/{id}", ...options });
  }

  public static questionGet<ThrowOnError extends boolean = false>(
    options: Options<QuestionGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      QuestionGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/{id}", ...options });
  }

  public static questionReadWithSorting<ThrowOnError extends boolean = false>(
    options: Options<QuestionReadWithSortingData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      QuestionReadWithSortingResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/sorted", ...options });
  }

  public static questionGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<QuestionGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/schema", ...options });
  }

  public static questionCount<ThrowOnError extends boolean = false>(
    options?: Options<QuestionCountData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      QuestionCountResponses,
      unknown,
      ThrowOnError
    >({ url: "/questions/count", ...options });
  }
}

export class UserController {
  public static userUpsert<ThrowOnError extends boolean = false>(
    options: Options<UserUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UserUpsertResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/users",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static userSyncUser<ThrowOnError extends boolean = false>(
    options: Options<UserSyncUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UserSyncUserResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/users/sync",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static userDelete<ThrowOnError extends boolean = false>(
    options: Options<UserDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      UserDeleteResponses,
      unknown,
      ThrowOnError
    >({ url: "/api/users/{id}", ...options });
  }

  public static userGet<ThrowOnError extends boolean = false>(
    options: Options<UserGetData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      UserGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/api/users/{id}", ...options });
  }

  public static userGetSchema<ThrowOnError extends boolean = false>(
    options?: Options<UserGetSchemaData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UserGetSchemaResponses,
      unknown,
      ThrowOnError
    >({ url: "/api/users/schema", ...options });
  }

  public static userGetByProviderId<ThrowOnError extends boolean = false>(
    options: Options<UserGetByProviderIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      UserGetByProviderIdResponses,
      unknown,
      ThrowOnError
    >({ url: "/api/users/provider/{providerId}", ...options });
  }

  public static userGetByEmail<ThrowOnError extends boolean = false>(
    options: Options<UserGetByEmailData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      UserGetByEmailResponses,
      unknown,
      ThrowOnError
    >({ url: "/api/users/email/{email}", ...options });
  }
}

export class PresignController {
  public static presignCreatePresignUrl<ThrowOnError extends boolean = false>(
    options: Options<PresignCreatePresignUrlData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PresignCreatePresignUrlResponses,
      unknown,
      ThrowOnError
    >({
      url: "/api/presign",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class HealthController {
  public static healthHealth<ThrowOnError extends boolean = false>(
    options?: Options<HealthHealthData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      HealthHealthResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/health",
      ...options,
    });
  }
}
