// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8080" | (string & {});
};

export type JsonNode = unknown;

export type SessionStateDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  sessionId?: string;
  questionId?: string;
  tldrawSnapshot?: JsonNode;
};

export type GenericResponseSessionStateDto = {
  data?: SessionStateDto;
  message?: string;
};

export type SessionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  userId?: string;
  questionIds?: Array<string>;
  startTime?: string;
  endTime?: string;
  status?: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
  score?: number;
  totalQuestions?: number;
  correctAnswers?: number;
  incorrectAnswers?: number;
  unanswered?: number;
  answers?: {
    [key: string]: string;
  };
  timeSpentSeconds?: number;
  examType?: "JEE_ADVANCED" | "JEE_MAIN" | "NEET" | "MIXED";
  subject?: "PHYSICS" | "CHEMISTRY" | "MATHEMATICS" | "BIOLOGY" | "MIXED";
};

export type GenericResponseSessionDto = {
  data?: SessionDto;
  message?: string;
};

export type QuestionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  questionText?: string;
  latexQuestionText?: string;
  subject?: "PHYSICS" | "CHEMISTRY" | "MATHEMATICS" | "BIOLOGY";
  examType?: "JEE_ADVANCED" | "JEE_MAIN" | "NEET";
  difficulty?: "EASY" | "MEDIUM" | "HARD";
  options?: Array<string>;
  correctAnswer?: string;
  explanation?: string;
  imageUrls?: Array<string>;
  year?: number;
  paperNumber?: number;
  questionNumber?: number;
  tags?: Array<string>;
  topic?: string;
  marks?: number;
  negativeMarks?: number;
  isActive?: boolean;
  metadata?: {
    [key: string]: string;
  };
};

export type GenericResponseQuestionDto = {
  data?: QuestionDto;
  message?: string;
};

export type UserDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  email?: string;
  name?: string;
  avatarUrl?: string;
  provider?: string;
  providerId?: string;
  lastLoginAt?: string;
};

export type GenericResponseUserDto = {
  data?: UserDto;
  message?: string;
};

export type UserSyncRequest = {
  email?: string;
  name?: string;
  avatarUrl?: string;
  provider?: string;
  providerId?: string;
};

export type PresignUrlRequest = {
  bucket: string;
  key: string;
  expiresInMinutes?: number;
};

export type PresignUrlResponse = {
  url?: string;
  expiration?: string;
};

export type GenericResponseListSessionDto = {
  data?: Array<SessionDto>;
  message?: string;
};

export type GenericResponseJsonNode = {
  data?: JsonNode;
  message?: string;
};

export type GenericResponseLong = {
  data?: number;
  message?: string;
};

export type GenericResponseListQuestionDto = {
  data?: Array<QuestionDto>;
  message?: string;
};

export type GenericResponseString = {
  data?: string;
  message?: string;
};

export type SessionstateGetStateData = {
  body?: never;
  path?: never;
  query: {
    sessionId: string;
    questionId: string;
  };
  url: "/session-states";
};

export type SessionstateGetStateResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionStateDto;
};

export type SessionstateGetStateResponse =
  SessionstateGetStateResponses[keyof SessionstateGetStateResponses];

export type SessionstateUpsertStateData = {
  body: SessionStateDto;
  path?: never;
  query?: never;
  url: "/session-states";
};

export type SessionstateUpsertStateResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionStateDto;
};

export type SessionstateUpsertStateResponse =
  SessionstateUpsertStateResponses[keyof SessionstateUpsertStateResponses];

export type SessionReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/sessions";
};

export type SessionReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListSessionDto;
};

export type SessionReadResponse =
  SessionReadResponses[keyof SessionReadResponses];

export type SessionUpsertData = {
  body: SessionDto;
  path?: never;
  query?: never;
  url: "/sessions";
};

export type SessionUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type SessionUpsertResponse =
  SessionUpsertResponses[keyof SessionUpsertResponses];

export type QuestionReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/questions";
};

export type QuestionReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListQuestionDto;
};

export type QuestionReadResponse =
  QuestionReadResponses[keyof QuestionReadResponses];

export type QuestionUpsertData = {
  body: QuestionDto;
  path?: never;
  query?: never;
  url: "/questions";
};

export type QuestionUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionUpsertResponse =
  QuestionUpsertResponses[keyof QuestionUpsertResponses];

export type UserUpsertData = {
  body: UserDto;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type UserUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserUpsertResponse = UserUpsertResponses[keyof UserUpsertResponses];

export type UserSyncUserData = {
  body: UserSyncRequest;
  path?: never;
  query?: never;
  url: "/api/users/sync";
};

export type UserSyncUserResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type UserSyncUserResponse =
  UserSyncUserResponses[keyof UserSyncUserResponses];

export type PresignCreatePresignUrlData = {
  body: PresignUrlRequest;
  path?: never;
  query?: never;
  url: "/api/presign";
};

export type PresignCreatePresignUrlResponses = {
  /**
   * OK
   */
  200: PresignUrlResponse;
};

export type PresignCreatePresignUrlResponse =
  PresignCreatePresignUrlResponses[keyof PresignCreatePresignUrlResponses];

export type SessionDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}";
};

export type SessionDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type SessionDeleteResponse =
  SessionDeleteResponses[keyof SessionDeleteResponses];

export type SessionGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}";
};

export type SessionGetResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type SessionGetResponse = SessionGetResponses[keyof SessionGetResponses];

export type SessionReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/sessions/sorted";
};

export type SessionReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListSessionDto;
};

export type SessionReadWithSortingResponse =
  SessionReadWithSortingResponses[keyof SessionReadWithSortingResponses];

export type SessionGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sessions/schema";
};

export type SessionGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type SessionGetSchemaResponse =
  SessionGetSchemaResponses[keyof SessionGetSchemaResponses];

export type SessionCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sessions/count";
};

export type SessionCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type SessionCountResponse =
  SessionCountResponses[keyof SessionCountResponses];

export type QuestionDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/questions/{id}";
};

export type QuestionDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionDeleteResponse =
  QuestionDeleteResponses[keyof QuestionDeleteResponses];

export type QuestionGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/questions/{id}";
};

export type QuestionGetResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionGetResponse =
  QuestionGetResponses[keyof QuestionGetResponses];

export type QuestionReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/questions/sorted";
};

export type QuestionReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListQuestionDto;
};

export type QuestionReadWithSortingResponse =
  QuestionReadWithSortingResponses[keyof QuestionReadWithSortingResponses];

export type QuestionGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/questions/schema";
};

export type QuestionGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type QuestionGetSchemaResponse =
  QuestionGetSchemaResponses[keyof QuestionGetSchemaResponses];

export type QuestionCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/questions/count";
};

export type QuestionCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type QuestionCountResponse =
  QuestionCountResponses[keyof QuestionCountResponses];

export type HealthHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthResponses = {
  /**
   * OK
   */
  200: GenericResponseString;
};

export type HealthHealthResponse =
  HealthHealthResponses[keyof HealthHealthResponses];

export type UserDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UserDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserDeleteResponse = UserDeleteResponses[keyof UserDeleteResponses];

export type UserGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UserGetResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserGetResponse = UserGetResponses[keyof UserGetResponses];

export type UserGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/schema";
};

export type UserGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type UserGetSchemaResponse =
  UserGetSchemaResponses[keyof UserGetSchemaResponses];

export type UserGetByProviderIdData = {
  body?: never;
  path: {
    providerId: string;
  };
  query?: never;
  url: "/api/users/provider/{providerId}";
};

export type UserGetByProviderIdResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type UserGetByProviderIdResponse =
  UserGetByProviderIdResponses[keyof UserGetByProviderIdResponses];

export type UserGetByEmailData = {
  body?: never;
  path: {
    email: string;
  };
  query?: never;
  url: "/api/users/email/{email}";
};

export type UserGetByEmailResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type UserGetByEmailResponse =
  UserGetByEmailResponses[keyof UserGetByEmailResponses];
