// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8080" | (string & {});
};

export type JsonNode = unknown;

export type SessionStateDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  sessionId?: string;
  questionId?: string;
  drawingStrokes?: JsonNode;
};

export type GenericResponseSessionStateDto = {
  data?: SessionStateDto;
  message?: string;
};

export type GenericResponseWaitlistRequestDto = {
  data?: WaitlistRequestDto;
  message?: string;
};

export type WaitlistRequestDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  email?: string;
  name?: string;
  message?: string;
  status?: "PENDING" | "APPROVED" | "REJECTED";
};

export type TutorDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  name?: string;
  title?: string;
  description?: string;
  avatarUrl?: string;
  voiceId?: string;
  personaPrompt?: string;
  active?: boolean;
};

export type GenericResponseTutorDto = {
  data?: TutorDto;
  message?: string;
};

export type SolutionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  questionId?: string;
  hints?: string;
  solution?: string;
};

export type GenericResponseSolutionDto = {
  data?: SolutionDto;
  message?: string;
};

export type SessionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  state?: string;
  previousState?: string;
  userId?: string;
  questionIds?: Array<string>;
  startTime?: string;
  endTime?: string;
  score?: number;
  totalQuestions?: number;
  correctAnswers?: number;
  incorrectAnswers?: number;
  unanswered?: number;
  answers?: {
    [key: string]: string;
  };
  timeSpentSeconds?: number;
  timeLeftSeconds?: number;
  examType?: "JEE_ADVANCED" | "JEE_MAIN" | "NEET" | "MIXED";
  subject?: "PHYSICS" | "CHEMISTRY" | "MATHEMATICS" | "BIOLOGY" | "MIXED";
};

export type GenericResponseSessionDto = {
  data?: SessionDto;
  message?: string;
};

export type QuestionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  questionText?: string;
  latexQuestionText?: string;
  subject?: "PHYSICS" | "CHEMISTRY" | "MATHEMATICS" | "BIOLOGY";
  examType?: "JEE_ADVANCED" | "JEE_MAIN" | "NEET";
  difficulty?: "EASY" | "MEDIUM" | "HARD";
  options?: Array<string>;
  correctAnswer?: string;
  explanation?: string;
  imageUrls?: Array<string>;
  year?: number;
  paperNumber?: number;
  questionNumber?: number;
  tags?: Array<string>;
  topic?: string;
  marks?: number;
  negativeMarks?: number;
  isActive?: boolean;
  metadata?: {
    [key: string]: string;
  };
};

export type GenericResponseQuestionDto = {
  data?: QuestionDto;
  message?: string;
};

export type LearningSessionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  questionId?: string;
  tutorId?: string;
  userId?: string;
  audioUrl?: string;
  transcript?: string;
  segments?: string;
  wordTimestamps?: WordTimestamps;
};

export type WordTimestamps = {
  words?: Array<string>;
  start?: Array<number>;
  end?: Array<number>;
};

export type GenericResponseLearningSessionDto = {
  data?: LearningSessionDto;
  message?: string;
};

export type UserDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  email?: string;
  name?: string;
  avatarUrl?: string;
  provider?: string;
  providerId?: string;
  lastLoginAt?: string;
  approved?: boolean;
  admin?: boolean;
};

export type GenericResponseUserDto = {
  data?: UserDto;
  message?: string;
};

export type WaitlistSubmitRequest = {
  email?: string;
  name?: string;
  message?: string;
};

export type UserSyncRequest = {
  email?: string;
  name?: string;
  avatarUrl?: string;
  provider?: string;
  providerId?: string;
};

export type InviteRequest = {
  email?: string;
};

export type PresignUrlRequest = {
  bucket: string;
  key: string;
  expiresInMinutes?: number;
};

export type PresignUrlResponse = {
  url?: string;
  expiration?: string;
};

export type AgentSessionDto = {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  state?: string;
  previousState?: string;
  userId?: string;
  taskArn?: string;
  workerUrl?: string;
  opencodeProjectId?: string;
  opencodeSessionId?: string;
  tokenUsage?: number;
  cost?: number;
  sessionTokenCap?: number;
  sessionCostCap?: number;
};

export type GenericResponseAgentSessionDto = {
  data?: AgentSessionDto;
  message?: string;
};

export type AgentSessionCreateRequest = {
  userId: string;
  sessionTokenCap?: number;
  sessionCostCap?: number;
};

export type GenericResponseListTutorDto = {
  data?: Array<TutorDto>;
  message?: string;
};

export type GenericResponseJsonNode = {
  data?: JsonNode;
  message?: string;
};

export type GenericResponseLong = {
  data?: number;
  message?: string;
};

export type GenericResponseListSolutionDto = {
  data?: Array<SolutionDto>;
  message?: string;
};

export type GenericResponseListSessionDto = {
  data?: Array<SessionDto>;
  message?: string;
};

export type GenericResponseString = {
  data?: string;
  message?: string;
};

export type GenericResponseListString = {
  data?: Array<string>;
  message?: string;
};

export type GenericResponseListQuestionDto = {
  data?: Array<QuestionDto>;
  message?: string;
};

export type GenericResponseListLearningSessionDto = {
  data?: Array<LearningSessionDto>;
  message?: string;
};

export type GenericResponseListWaitlistRequestDto = {
  data?: Array<WaitlistRequestDto>;
  message?: string;
};

export type GenericResponseListAgentSessionDto = {
  data?: Array<AgentSessionDto>;
  message?: string;
};

export type GenericResponseMapStringObject = {
  data?: {
    [key: string]: unknown;
  };
  message?: string;
};

export type AgentMessageDto = {
  id?: string;
  productSessionId?: string;
  opencodeSessionId?: string;
  role?: string;
  agent?: string;
  modelId?: string;
  providerId?: string;
  cost?: number;
  tokensInput?: number;
  tokensOutput?: number;
  tokensReasoning?: number;
  error?: string;
  createdAt?: string;
  completedAt?: string;
  parts?: Array<AgentPartDto>;
};

export type AgentPartDto = {
  id?: string;
  messageId?: string;
  productSessionId?: string;
  opencodeSessionId?: string;
  type?: string;
  toolName?: string;
  toolCallId?: string;
  toolStatus?: string;
  data?: string;
  syncedAt?: string;
};

export type GenericResponseListAgentMessageDto = {
  data?: Array<AgentMessageDto>;
  message?: string;
};

export type GenericResponseBoolean = {
  data?: boolean;
  message?: string;
};

export type AgentArtifactDto = {
  id?: string;
  productSessionId?: string;
  messageId?: string;
  partId?: string;
  storageKey?: string;
  mime?: string;
  bytes?: number;
  sha256?: string;
  createdAt?: string;
};

export type GenericResponseListAgentArtifactDto = {
  data?: Array<AgentArtifactDto>;
  message?: string;
};

export type GenericResponsePresignUrlResponse = {
  data?: PresignUrlResponse;
  message?: string;
};

export type SessionstateGetStateData = {
  body?: never;
  path?: never;
  query: {
    sessionId: string;
    questionId: string;
  };
  url: "/session-states";
};

export type SessionstateGetStateResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionStateDto;
};

export type SessionstateGetStateResponse =
  SessionstateGetStateResponses[keyof SessionstateGetStateResponses];

export type SessionstateUpsertStateData = {
  body: SessionStateDto;
  path?: never;
  query?: never;
  url: "/session-states";
};

export type SessionstateUpsertStateResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionStateDto;
};

export type SessionstateUpsertStateResponse =
  SessionstateUpsertStateResponses[keyof SessionstateUpsertStateResponses];

export type WaitlistrequestRejectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/waitlist/{id}/reject";
};

export type WaitlistrequestRejectResponses = {
  /**
   * OK
   */
  200: GenericResponseWaitlistRequestDto;
};

export type WaitlistrequestRejectResponse =
  WaitlistrequestRejectResponses[keyof WaitlistrequestRejectResponses];

export type WaitlistrequestApproveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/waitlist/{id}/approve";
};

export type WaitlistrequestApproveResponses = {
  /**
   * OK
   */
  200: GenericResponseWaitlistRequestDto;
};

export type WaitlistrequestApproveResponse =
  WaitlistrequestApproveResponses[keyof WaitlistrequestApproveResponses];

export type TutorReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/tutors";
};

export type TutorReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListTutorDto;
};

export type TutorReadResponse = TutorReadResponses[keyof TutorReadResponses];

export type TutorUpsertData = {
  body: TutorDto;
  path?: never;
  query?: never;
  url: "/tutors";
};

export type TutorUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseTutorDto;
};

export type TutorUpsertResponse =
  TutorUpsertResponses[keyof TutorUpsertResponses];

export type SolutionReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/solutions";
};

export type SolutionReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListSolutionDto;
};

export type SolutionReadResponse =
  SolutionReadResponses[keyof SolutionReadResponses];

export type SolutionUpsertData = {
  body: SolutionDto;
  path?: never;
  query?: never;
  url: "/solutions";
};

export type SolutionUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseSolutionDto;
};

export type SolutionUpsertResponse =
  SolutionUpsertResponses[keyof SolutionUpsertResponses];

export type ReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/sessions";
};

export type ReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListSessionDto;
};

export type ReadResponse = ReadResponses[keyof ReadResponses];

export type UpsertData = {
  body: SessionDto;
  path?: never;
  query?: never;
  url: "/sessions";
};

export type UpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type UpsertResponse = UpsertResponses[keyof UpsertResponses];

export type TransitionData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    event: string;
  };
  url: "/sessions/{id}/transition";
};

export type TransitionResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type TransitionResponse = TransitionResponses[keyof TransitionResponses];

export type QuestionReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/questions";
};

export type QuestionReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListQuestionDto;
};

export type QuestionReadResponse =
  QuestionReadResponses[keyof QuestionReadResponses];

export type QuestionUpsertData = {
  body: QuestionDto;
  path?: never;
  query?: never;
  url: "/questions";
};

export type QuestionUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionUpsertResponse =
  QuestionUpsertResponses[keyof QuestionUpsertResponses];

export type LearningsessionReadData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/learning-sessions";
};

export type LearningsessionReadResponses = {
  /**
   * OK
   */
  200: GenericResponseListLearningSessionDto;
};

export type LearningsessionReadResponse =
  LearningsessionReadResponses[keyof LearningsessionReadResponses];

export type LearningsessionUpsertData = {
  body: LearningSessionDto;
  path?: never;
  query?: never;
  url: "/learning-sessions";
};

export type LearningsessionUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseLearningSessionDto;
};

export type LearningsessionUpsertResponse =
  LearningsessionUpsertResponses[keyof LearningsessionUpsertResponses];

export type UserUpsertData = {
  body: UserDto;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type UserUpsertResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserUpsertResponse = UserUpsertResponses[keyof UserUpsertResponses];

export type WaitlistrequestListData = {
  body?: never;
  path?: never;
  query?: {
    status?: string;
  };
  url: "/api/users/waitlist";
};

export type WaitlistrequestListResponses = {
  /**
   * OK
   */
  200: GenericResponseListWaitlistRequestDto;
};

export type WaitlistrequestListResponse =
  WaitlistrequestListResponses[keyof WaitlistrequestListResponses];

export type WaitlistrequestSubmitData = {
  body: WaitlistSubmitRequest;
  path?: never;
  query?: never;
  url: "/api/users/waitlist";
};

export type WaitlistrequestSubmitResponses = {
  /**
   * OK
   */
  200: GenericResponseWaitlistRequestDto;
};

export type WaitlistrequestSubmitResponse =
  WaitlistrequestSubmitResponses[keyof WaitlistrequestSubmitResponses];

export type UserSyncUserData = {
  body: UserSyncRequest;
  path?: never;
  query?: never;
  url: "/api/users/sync";
};

export type UserSyncUserResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserSyncUserResponse =
  UserSyncUserResponses[keyof UserSyncUserResponses];

export type UserInviteUserData = {
  body: InviteRequest;
  path?: never;
  query?: never;
  url: "/api/users/invite";
};

export type UserInviteUserResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserInviteUserResponse =
  UserInviteUserResponses[keyof UserInviteUserResponses];

export type PresignCreatePresignUrlData = {
  body: PresignUrlRequest;
  path?: never;
  query?: never;
  url: "/api/presign";
};

export type PresignCreatePresignUrlResponses = {
  /**
   * OK
   */
  200: PresignUrlResponse;
};

export type PresignCreatePresignUrlResponse =
  PresignCreatePresignUrlResponses[keyof PresignCreatePresignUrlResponses];

export type Read1Data = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    size?: string;
  };
  url: "/api/agent-sessions";
};

export type Read1Responses = {
  /**
   * OK
   */
  200: GenericResponseListAgentSessionDto;
};

export type Read1Response = Read1Responses[keyof Read1Responses];

export type Upsert1Data = {
  body: AgentSessionDto;
  path?: never;
  query?: never;
  url: "/api/agent-sessions";
};

export type Upsert1Responses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type Upsert1Response = Upsert1Responses[keyof Upsert1Responses];

export type Transition1Data = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    event: string;
  };
  url: "/api/agent-sessions/{id}/transition";
};

export type Transition1Responses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type Transition1Response =
  Transition1Responses[keyof Transition1Responses];

export type TerminateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/terminate";
};

export type TerminateResponses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type TerminateResponse = TerminateResponses[keyof TerminateResponses];

export type CreateData = {
  body: AgentSessionCreateRequest;
  path?: never;
  query?: never;
  url: "/api/agent-sessions/create";
};

export type CreateResponses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type TutorDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/tutors/{id}";
};

export type TutorDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseTutorDto;
};

export type TutorDeleteResponse =
  TutorDeleteResponses[keyof TutorDeleteResponses];

export type TutorGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/tutors/{id}";
};

export type TutorGetResponses = {
  /**
   * OK
   */
  200: GenericResponseTutorDto;
};

export type TutorGetResponse = TutorGetResponses[keyof TutorGetResponses];

export type TutorReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/tutors/sorted";
};

export type TutorReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListTutorDto;
};

export type TutorReadWithSortingResponse =
  TutorReadWithSortingResponses[keyof TutorReadWithSortingResponses];

export type TutorGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tutors/schema";
};

export type TutorGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type TutorGetSchemaResponse =
  TutorGetSchemaResponses[keyof TutorGetSchemaResponses];

export type TutorCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tutors/count";
};

export type TutorCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type TutorCountResponse = TutorCountResponses[keyof TutorCountResponses];

export type TutorGetActiveTutorsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/tutors/active";
};

export type TutorGetActiveTutorsResponses = {
  /**
   * OK
   */
  200: GenericResponseListTutorDto;
};

export type TutorGetActiveTutorsResponse =
  TutorGetActiveTutorsResponses[keyof TutorGetActiveTutorsResponses];

export type SolutionDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/solutions/{id}";
};

export type SolutionDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseSolutionDto;
};

export type SolutionDeleteResponse =
  SolutionDeleteResponses[keyof SolutionDeleteResponses];

export type SolutionGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/solutions/{id}";
};

export type SolutionGetResponses = {
  /**
   * OK
   */
  200: GenericResponseSolutionDto;
};

export type SolutionGetResponse =
  SolutionGetResponses[keyof SolutionGetResponses];

export type SolutionReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/solutions/sorted";
};

export type SolutionReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListSolutionDto;
};

export type SolutionReadWithSortingResponse =
  SolutionReadWithSortingResponses[keyof SolutionReadWithSortingResponses];

export type SolutionGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/solutions/schema";
};

export type SolutionGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type SolutionGetSchemaResponse =
  SolutionGetSchemaResponses[keyof SolutionGetSchemaResponses];

export type SolutionGetByQuestionIdData = {
  body?: never;
  path: {
    questionId: string;
  };
  query?: never;
  url: "/solutions/question/{questionId}";
};

export type SolutionGetByQuestionIdResponses = {
  /**
   * OK
   */
  200: GenericResponseSolutionDto;
};

export type SolutionGetByQuestionIdResponse =
  SolutionGetByQuestionIdResponses[keyof SolutionGetByQuestionIdResponses];

export type SolutionCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/solutions/count";
};

export type SolutionCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type SolutionCountResponse =
  SolutionCountResponses[keyof SolutionCountResponses];

export type DeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}";
};

export type DeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type GetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}";
};

export type GetResponses = {
  /**
   * OK
   */
  200: GenericResponseSessionDto;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type DebugData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}/debug";
};

export type DebugResponses = {
  /**
   * OK
   */
  200: GenericResponseString;
};

export type DebugResponse = DebugResponses[keyof DebugResponses];

export type AvailableEventsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/sessions/{id}/available-events";
};

export type AvailableEventsResponses = {
  /**
   * OK
   */
  200: GenericResponseListString;
};

export type AvailableEventsResponse =
  AvailableEventsResponses[keyof AvailableEventsResponses];

export type ReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/sessions/sorted";
};

export type ReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListSessionDto;
};

export type ReadWithSortingResponse =
  ReadWithSortingResponses[keyof ReadWithSortingResponses];

export type GetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sessions/schema";
};

export type GetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type GetSchemaResponse = GetSchemaResponses[keyof GetSchemaResponses];

export type CountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sessions/count";
};

export type CountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type CountResponse = CountResponses[keyof CountResponses];

export type QuestionDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/questions/{id}";
};

export type QuestionDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionDeleteResponse =
  QuestionDeleteResponses[keyof QuestionDeleteResponses];

export type QuestionGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/questions/{id}";
};

export type QuestionGetResponses = {
  /**
   * OK
   */
  200: GenericResponseQuestionDto;
};

export type QuestionGetResponse =
  QuestionGetResponses[keyof QuestionGetResponses];

export type QuestionReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/questions/sorted";
};

export type QuestionReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListQuestionDto;
};

export type QuestionReadWithSortingResponse =
  QuestionReadWithSortingResponses[keyof QuestionReadWithSortingResponses];

export type QuestionGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/questions/schema";
};

export type QuestionGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type QuestionGetSchemaResponse =
  QuestionGetSchemaResponses[keyof QuestionGetSchemaResponses];

export type QuestionCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/questions/count";
};

export type QuestionCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type QuestionCountResponse =
  QuestionCountResponses[keyof QuestionCountResponses];

export type LearningsessionDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/learning-sessions/{id}";
};

export type LearningsessionDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseLearningSessionDto;
};

export type LearningsessionDeleteResponse =
  LearningsessionDeleteResponses[keyof LearningsessionDeleteResponses];

export type LearningsessionGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/learning-sessions/{id}";
};

export type LearningsessionGetResponses = {
  /**
   * OK
   */
  200: GenericResponseLearningSessionDto;
};

export type LearningsessionGetResponse =
  LearningsessionGetResponses[keyof LearningsessionGetResponses];

export type LearningsessionGetByUserIdData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: "/learning-sessions/user/{userId}";
};

export type LearningsessionGetByUserIdResponses = {
  /**
   * OK
   */
  200: GenericResponseListLearningSessionDto;
};

export type LearningsessionGetByUserIdResponse =
  LearningsessionGetByUserIdResponses[keyof LearningsessionGetByUserIdResponses];

export type LearningsessionReadWithSortingData = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/learning-sessions/sorted";
};

export type LearningsessionReadWithSortingResponses = {
  /**
   * OK
   */
  200: GenericResponseListLearningSessionDto;
};

export type LearningsessionReadWithSortingResponse =
  LearningsessionReadWithSortingResponses[keyof LearningsessionReadWithSortingResponses];

export type LearningsessionGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/learning-sessions/schema";
};

export type LearningsessionGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type LearningsessionGetSchemaResponse =
  LearningsessionGetSchemaResponses[keyof LearningsessionGetSchemaResponses];

export type LearningsessionGetByQuestionIdData = {
  body?: never;
  path: {
    questionId: string;
  };
  query?: never;
  url: "/learning-sessions/question/{questionId}";
};

export type LearningsessionGetByQuestionIdResponses = {
  /**
   * OK
   */
  200: GenericResponseListLearningSessionDto;
};

export type LearningsessionGetByQuestionIdResponse =
  LearningsessionGetByQuestionIdResponses[keyof LearningsessionGetByQuestionIdResponses];

export type LearningsessionGetByQuestionAndTutorData = {
  body?: never;
  path: {
    questionId: string;
    tutorId: string;
  };
  query?: never;
  url: "/learning-sessions/question/{questionId}/tutor/{tutorId}";
};

export type LearningsessionGetByQuestionAndTutorResponses = {
  /**
   * OK
   */
  200: GenericResponseLearningSessionDto;
};

export type LearningsessionGetByQuestionAndTutorResponse =
  LearningsessionGetByQuestionAndTutorResponses[keyof LearningsessionGetByQuestionAndTutorResponses];

export type LearningsessionCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/learning-sessions/count";
};

export type LearningsessionCountResponses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type LearningsessionCountResponse =
  LearningsessionCountResponses[keyof LearningsessionCountResponses];

export type HealthHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthResponses = {
  /**
   * OK
   */
  200: GenericResponseString;
};

export type HealthHealthResponse =
  HealthHealthResponses[keyof HealthHealthResponses];

export type UserDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UserDeleteResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserDeleteResponse = UserDeleteResponses[keyof UserDeleteResponses];

export type UserGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UserGetResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserGetResponse = UserGetResponses[keyof UserGetResponses];

export type WaitlistrequestGetByEmailData = {
  body?: never;
  path: {
    email: string;
  };
  query?: never;
  url: "/api/users/waitlist/email/{email}";
};

export type WaitlistrequestGetByEmailResponses = {
  /**
   * OK
   */
  200: GenericResponseWaitlistRequestDto;
};

export type WaitlistrequestGetByEmailResponse =
  WaitlistrequestGetByEmailResponses[keyof WaitlistrequestGetByEmailResponses];

export type UserGetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/schema";
};

export type UserGetSchemaResponses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type UserGetSchemaResponse =
  UserGetSchemaResponses[keyof UserGetSchemaResponses];

export type UserGetByProviderIdData = {
  body?: never;
  path: {
    providerId: string;
  };
  query?: never;
  url: "/api/users/provider/{providerId}";
};

export type UserGetByProviderIdResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserGetByProviderIdResponse =
  UserGetByProviderIdResponses[keyof UserGetByProviderIdResponses];

export type UserGetMeData = {
  body?: never;
  path?: never;
  query: {
    email: string;
  };
  url: "/api/users/me";
};

export type UserGetMeResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserGetMeResponse = UserGetMeResponses[keyof UserGetMeResponses];

export type UserGetByEmailData = {
  body?: never;
  path: {
    email: string;
  };
  query?: never;
  url: "/api/users/email/{email}";
};

export type UserGetByEmailResponses = {
  /**
   * OK
   */
  200: GenericResponseUserDto;
};

export type UserGetByEmailResponse =
  UserGetByEmailResponses[keyof UserGetByEmailResponses];

export type Delete1Data = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}";
};

export type Delete1Responses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type Delete1Response = Delete1Responses[keyof Delete1Responses];

export type Get1Data = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}";
};

export type Get1Responses = {
  /**
   * OK
   */
  200: GenericResponseAgentSessionDto;
};

export type Get1Response = Get1Responses[keyof Get1Responses];

export type StatusData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/status";
};

export type StatusResponses = {
  /**
   * OK
   */
  200: GenericResponseMapStringObject;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type MessagesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/messages";
};

export type MessagesResponses = {
  /**
   * OK
   */
  200: GenericResponseListAgentMessageDto;
};

export type MessagesResponse = MessagesResponses[keyof MessagesResponses];

export type HealthData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/health";
};

export type HealthResponses = {
  /**
   * OK
   */
  200: GenericResponseBoolean;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type Debug1Data = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/debug";
};

export type Debug1Responses = {
  /**
   * OK
   */
  200: GenericResponseString;
};

export type Debug1Response = Debug1Responses[keyof Debug1Responses];

export type AvailableEvents1Data = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/available-events";
};

export type AvailableEvents1Responses = {
  /**
   * OK
   */
  200: GenericResponseListString;
};

export type AvailableEvents1Response =
  AvailableEvents1Responses[keyof AvailableEvents1Responses];

export type ArtifactsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/artifacts";
};

export type ArtifactsResponses = {
  /**
   * OK
   */
  200: GenericResponseListAgentArtifactDto;
};

export type ArtifactsResponse = ArtifactsResponses[keyof ArtifactsResponses];

export type DownloadArtifactData = {
  body?: never;
  path: {
    id: string;
    artifactId: string;
  };
  query?: never;
  url: "/api/agent-sessions/{id}/artifacts/{artifactId}/download";
};

export type DownloadArtifactResponses = {
  /**
   * OK
   */
  200: GenericResponsePresignUrlResponse;
};

export type DownloadArtifactResponse =
  DownloadArtifactResponses[keyof DownloadArtifactResponses];

export type GetByUserIdData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: "/api/agent-sessions/user/{userId}";
};

export type GetByUserIdResponses = {
  /**
   * OK
   */
  200: GenericResponseListAgentSessionDto;
};

export type GetByUserIdResponse =
  GetByUserIdResponses[keyof GetByUserIdResponses];

export type ReadWithSorting1Data = {
  body?: never;
  path?: never;
  query: {
    direction: string;
    sortBy: string;
    page: string;
    size: string;
  };
  url: "/api/agent-sessions/sorted";
};

export type ReadWithSorting1Responses = {
  /**
   * OK
   */
  200: GenericResponseListAgentSessionDto;
};

export type ReadWithSorting1Response =
  ReadWithSorting1Responses[keyof ReadWithSorting1Responses];

export type GetSchema1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent-sessions/schema";
};

export type GetSchema1Responses = {
  /**
   * OK
   */
  200: GenericResponseJsonNode;
};

export type GetSchema1Response = GetSchema1Responses[keyof GetSchema1Responses];

export type Count1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent-sessions/count";
};

export type Count1Responses = {
  /**
   * OK
   */
  200: GenericResponseLong;
};

export type Count1Response = Count1Responses[keyof Count1Responses];
